# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_embedded_payroll_python_sdk.type.flsa_status_type import FlsaStatusType

class RequiredCompensation(TypedDict):
    pass

class OptionalCompensation(TypedDict, total=False):
    # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
    version: str

    # The UUID of the compensation in Gusto.
    uuid: str

    # The UUID of the job to which the compensation belongs.
    job_uuid: str

    # The dollar amount paid per payment unit.
    rate: str

    # The unit accompanying the compensation rate. If the employee is an owner, rate should be 'Paycheck'.
    payment_unit: str

    flsa_status: FlsaStatusType

    # The effective date for this compensation. For the first compensation, this defaults to the job's hire date.
    effective_date: str

    # Indicates if the compensation could be adjusted to minimum wage during payroll calculation.
    adjust_for_minimum_wage: bool

class Compensation(RequiredCompensation, OptionalCompensation):
    pass
