# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCompaniesAcceptTermsOfServiceResponse(TypedDict):
    pass

class OptionalCompaniesAcceptTermsOfServiceResponse(TypedDict, total=False):
    # Whether the latest terms have been accepted by the user.
    latest_terms_accepted: bool

class CompaniesAcceptTermsOfServiceResponse(RequiredCompaniesAcceptTermsOfServiceResponse, OptionalCompaniesAcceptTermsOfServiceResponse):
    pass
