# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_embedded_payroll_python_sdk.type.company_onboarding_status_onboarding_steps_item_requirements import CompanyOnboardingStatusOnboardingStepsItemRequirements

class RequiredCompanyOnboardingStatusOnboardingStepsItem(TypedDict):
    pass

class OptionalCompanyOnboardingStatusOnboardingStepsItem(TypedDict, total=False):
    # The display name of the onboarding step
    title: str

    # The string identifier for each onboarding step
    id: str

    # The boolean flag indicating whether the step is required or optional
    required: bool

    # The boolean flag indicating whether the step is completed or not.
    completed: bool

    # The boolean flag indicating whether the step can be skipped or not.
    skippable: bool

    requirements: CompanyOnboardingStatusOnboardingStepsItemRequirements

class CompanyOnboardingStatusOnboardingStepsItem(RequiredCompanyOnboardingStatusOnboardingStepsItem, OptionalCompanyOnboardingStatusOnboardingStepsItem):
    pass
