# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCompaniesMigrateToEmbeddedPayrollRequest(TypedDict):
    # Email of the company signatory who is authorized to accept our [Terms of Service](https://flows.gusto.com/terms) and migration decision. You can retrieve the signatory email from the `GET /v/1/companies/{company_id}/signatories` endpoint.
    email: str

    # The IP address of the signatory who viewed and accepted the Terms of Service.
    ip_address: str

    # The signatory's user ID on your platform.
    external_user_id: str

class OptionalCompaniesMigrateToEmbeddedPayrollRequest(TypedDict, total=False):
    pass

class CompaniesMigrateToEmbeddedPayrollRequest(RequiredCompaniesMigrateToEmbeddedPayrollRequest, OptionalCompaniesMigrateToEmbeddedPayrollRequest):
    pass
