# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredContractorPaymentsPreviewDebitDateResponse(TypedDict):
    pass

class OptionalContractorPaymentsPreviewDebitDateResponse(TypedDict, total=False):
    # The calculated debit date. If the payment method is Direct Deposit, the debit date will account for the company's ACH speed. If the payment method is Check, the debit date will be the same as the check date.
    expected_debit_date: str

class ContractorPaymentsPreviewDebitDateResponse(RequiredContractorPaymentsPreviewDebitDateResponse, OptionalContractorPaymentsPreviewDebitDateResponse):
    pass
