# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_embedded_payroll_python_sdk.type.contractor_onboarding_status_onboarding_steps import ContractorOnboardingStatusOnboardingSteps

class RequiredContractorOnboardingStatus(TypedDict):
    pass

class OptionalContractorOnboardingStatus(TypedDict, total=False):
    # Unique identifier for this contractor.
    uuid: str

    # One of the \"onboarding_status\" enum values.
    onboarding_status: str

    onboarding_steps: ContractorOnboardingStatusOnboardingSteps

class ContractorOnboardingStatus(RequiredContractorOnboardingStatus, OptionalContractorOnboardingStatus):
    pass
