# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredContractorsChangeOnboardingStatusRequest(TypedDict):
    # The updated onboarding status for the employee
    onboarding_status: str

class OptionalContractorsChangeOnboardingStatusRequest(TypedDict, total=False):
    pass

class ContractorsChangeOnboardingStatusRequest(RequiredContractorsChangeOnboardingStatusRequest, OptionalContractorsChangeOnboardingStatusRequest):
    pass
