# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredContractorPaymentReceiptContractorPaymentsItem(TypedDict):
    pass

class OptionalContractorPaymentReceiptContractorPaymentsItem(TypedDict, total=False):
    # The UUID of the contractor.
    contractor_uuid: str

    # The first name of the contractor. Applies when `contractor_type` is `Individual`.
    contractor_first_name: str

    # The last name of the contractor.  Applies when `contractor_type` is `Individual`.
    contractor_last_name: str

    # The business name of the employee. Applies when `contractor_type` is `Business`.
    contractor_business_name: str

    # The type of contractor.  `Individual` `Business`
    contractor_type: str

    # The payment method.  `Direct Deposit` `Check` `Historical Payment` `Correction Payment`
    payment_method: str

    # The fixed wage of the payment, regardless of hours worked.
    wage: str

    # The bonus amount in the payment.
    bonus: str

    # The reimbursement amount in the payment.
    reimbursement: str

class ContractorPaymentReceiptContractorPaymentsItem(RequiredContractorPaymentReceiptContractorPaymentsItem, OptionalContractorPaymentReceiptContractorPaymentsItem):
    pass
