# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmployeePayStub(TypedDict):
    pass

class OptionalEmployeePayStub(TypedDict, total=False):
    # The UUID of the employee pay stub.
    uuid: str

    # The check date of the pay stub.
    check_date: str

    # The gross pay amount for the pay stub.
    gross_pay: str

    # The net pay amount for the pay stub.
    net_pay: str

    # A unique identifier of the payroll to which the pay stub belongs.
    payroll_uuid: str

    # The check amount for the pay stub.
    check_amount: str

class EmployeePayStub(RequiredEmployeePayStub, OptionalEmployeePayStub):
    pass
