# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmployeeEmploymentsGetHistoryResponseItem(TypedDict):
    pass

class OptionalEmployeeEmploymentsGetHistoryResponseItem(TypedDict, total=False):
    # The employee's start day of work for an employment.
    hire_date: str

    # The employee's last day of work for an employment.
    termination_date: str

    # The boolean flag indicating whether Gusto will file a new hire report for the employee.
    file_new_hire_report: bool

    # Whether the employee is a two percent shareholder of the company. This field only applies to companies with an S-Corp entity type.
    two_percent_shareholder: bool

    # The employee's employment status. Supplying an invalid option will set the employment_status to *not_set*.
    employment_status: str

class EmployeeEmploymentsGetHistoryResponseItem(RequiredEmployeeEmploymentsGetHistoryResponseItem, OptionalEmployeeEmploymentsGetHistoryResponseItem):
    pass
