# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmployeeFormsGenerateW2DocumentRequest(TypedDict):
    # The employee UUID.
    employee_id: str

class OptionalEmployeeFormsGenerateW2DocumentRequest(TypedDict, total=False):
    # Must be equal to or more recent than 2015. If not specified, defaults to the previous year. 
    year: int

class EmployeeFormsGenerateW2DocumentRequest(RequiredEmployeeFormsGenerateW2DocumentRequest, OptionalEmployeeFormsGenerateW2DocumentRequest):
    pass
