# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_embedded_payroll_python_sdk.type.external_payroll_external_payroll_items_item_benefits import ExternalPayrollExternalPayrollItemsItemBenefits
from gusto_embedded_payroll_python_sdk.type.external_payroll_external_payroll_items_item_earnings import ExternalPayrollExternalPayrollItemsItemEarnings
from gusto_embedded_payroll_python_sdk.type.external_payroll_external_payroll_items_item_taxes import ExternalPayrollExternalPayrollItemsItemTaxes

class RequiredExternalPayrollExternalPayrollItemsItem(TypedDict):
    pass

class OptionalExternalPayrollExternalPayrollItemsItem(TypedDict, total=False):
    employee_uuid: str

    earnings: ExternalPayrollExternalPayrollItemsItemEarnings

    benefits: ExternalPayrollExternalPayrollItemsItemBenefits

    taxes: ExternalPayrollExternalPayrollItemsItemTaxes

class ExternalPayrollExternalPayrollItemsItem(RequiredExternalPayrollExternalPayrollItemsItem, OptionalExternalPayrollExternalPayrollItemsItem):
    pass
