# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_embedded_payroll_python_sdk.type.compensation import Compensation

class RequiredJob(TypedDict):
    pass

class OptionalJob(TypedDict, total=False):
    # The title for the job.
    title: typing.Optional[str]

    # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
    version: str

    # The UUID of the job.
    uuid: str

    # The UUID of the employee to which the job belongs.
    employee_uuid: str

    # The date when the employee was hired or rehired for the job.
    hire_date: str

    # Whether this is the employee's primary job. The value will be set to true unless an existing job exists for the employee.
    primary: bool

    # The current compensation rate of the job.
    rate: str

    # The payment unit of the current compensation for the job.
    payment_unit: str

    # The UUID of the current compensation of the job.
    current_compensation_uuid: str

    # Whether the employee owns at least 2% of the company.
    two_percent_shareholder: bool

    # Whether this job is eligible for workers' compensation coverage in the state of Washington (WA).
    state_wc_covered: bool

    # The risk class code for workers' compensation in Washington state. Please visit [Washington state's Risk Class page](https://www.lni.wa.gov/insurance/rates-risk-classes/risk-classes-for-workers-compensation/risk-class-lookup#/) to learn more.
    state_wc_class_code: str

    compensations: typing.List[Compensation]

class Job(RequiredJob, OptionalJob):
    pass
