# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_embedded_payroll_python_sdk.type.flsa_status_type import FlsaStatusType
from gusto_embedded_payroll_python_sdk.type.jobs_and_compensations_update_compensation_request_minimum_wages import JobsAndCompensationsUpdateCompensationRequestMinimumWages

class RequiredJobsAndCompensationsUpdateCompensationRequest(TypedDict):
    # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field.
    version: str

class OptionalJobsAndCompensationsUpdateCompensationRequest(TypedDict, total=False):
    # The dollar amount paid per payment unit.
    rate: str

    # The unit accompanying the compensation rate. If the employee is an owner, rate should be 'Paycheck'.
    payment_unit: str

    flsa_status: FlsaStatusType

    # Determines whether the compensation should be adjusted for minimum wage. Only applies to Nonexempt employees.
    adjust_for_minimum_wage: bool

    minimum_wages: JobsAndCompensationsUpdateCompensationRequestMinimumWages

class JobsAndCompensationsUpdateCompensationRequest(RequiredJobsAndCompensationsUpdateCompensationRequest, OptionalJobsAndCompensationsUpdateCompensationRequest):
    pass
