# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLocationsCreateCompanyLocationRequest1(TypedDict):
    phone_number: str

    street_1: str

    street_2: typing.Optional[str]

    city: str

    state: str

    zip: str

    country: str

class OptionalLocationsCreateCompanyLocationRequest1(TypedDict, total=False):
    pass

class LocationsCreateCompanyLocationRequest1(RequiredLocationsCreateCompanyLocationRequest1, OptionalLocationsCreateCompanyLocationRequest1):
    pass
