# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredNotificationResourcesItem(TypedDict):
    # The type of entity being described, could be “Contractor”, “Employee”, “BankAccount”, “Payroll”, “ContractorPayment”, “RecoveryCase”, or “Signatory”
    entity_type: str

    # Unique identifier of the entity
    entity_uuid: str

class OptionalNotificationResourcesItem(TypedDict, total=False):
    # Optional. The type of a resource that is related to the one described by entity_type and entity_uuid. For instance, if the entity_type is “BankAccount”, the reference_type could be the “Employee” or “Contractor” to whom the bank account belongs.
    reference_type: str

    # Optional. Unique identifier of the reference.
    reference_uuid: str

class NotificationResourcesItem(RequiredNotificationResourcesItem, OptionalNotificationResourcesItem):
    pass
