# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPaidTimeOff(TypedDict):
    pass

class OptionalPaidTimeOff(TypedDict, total=False):
    # The name of the paid time off type.
    name: str

    # The name of the time off policy.
    policy_name: str

    # The UUID of the time off policy.
    policy_uuid: str

    # The unit the PTO type is accrued in.
    accrual_unit: str

    # The number of accrual units accrued per accrual period.
    accrual_rate: str

    # The accrual method of the time off policy
    accrual_method: str

    # The frequency at which the PTO type is accrued.
    accrual_period: str

    # The number of accrual units accrued.
    accrual_balance: str

    # The maximum number of accrual units allowed. A null value signifies no maximum.
    maximum_accrual_balance: typing.Optional[str]

    # Whether the accrual balance is paid to the employee upon termination.
    paid_at_termination: bool

class PaidTimeOff(RequiredPaidTimeOff, OptionalPaidTimeOff):
    pass
