# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayrollPayPeriodType(TypedDict):
    pass

class OptionalPayrollPayPeriodType(TypedDict, total=False):
    # The start date, inclusive, of the pay period.
    start_date: str

    # The start date, inclusive, of the pay period.
    end_date: str

    # The UUID of the pay schedule for the payroll.
    pay_schedule_uuid: typing.Optional[str]

class PayrollPayPeriodType(RequiredPayrollPayPeriodType, OptionalPayrollPayPeriodType):
    pass
