# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayrollPayrollStatusMetaType(TypedDict):
    pass

class OptionalPayrollPayrollStatusMetaType(TypedDict, total=False):
    # true if the payroll may be cancelled
    cancellable: bool

    # The date an employee will be paid if the payroll is submitted now
    expected_check_date: str

    # The normal check date for the associated pay period
    initial_check_date: str

    # The time the employer's account will be debited if the payroll is submitted now
    expected_debit_time: str

    # expected_check_date > initial_check_date
    payroll_late: bool

    # Payroll must be submitted at or before this time to avoid late payroll
    initial_debit_cutoff_time: str

class PayrollPayrollStatusMetaType(RequiredPayrollPayrollStatusMetaType, OptionalPayrollPayrollStatusMetaType):
    pass
