# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTimeOffPoliciesCalculateAccruingTimeOffHoursRequest(TypedDict):
    pass

class OptionalTimeOffPoliciesCalculateAccruingTimeOffHoursRequest(TypedDict, total=False):
    # regular hours worked in this pay period
    regular_hours_worked: typing.Union[int, float]

    # overtime hours worked in this pay period
    overtime_hours_worked: typing.Union[int, float]

    # double overtime hours worked in this pay period
    double_overtime_hours_worked: typing.Union[int, float]

    # paid time off hours used in this pay period
    pto_hours_used: typing.Union[int, float]

    # sick hours used in this pay period
    sick_hours_used: typing.Union[int, float]

class TimeOffPoliciesCalculateAccruingTimeOffHoursRequest(RequiredTimeOffPoliciesCalculateAccruingTimeOffHoursRequest, OptionalTimeOffPoliciesCalculateAccruingTimeOffHoursRequest):
    pass
