# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from gusto_embedded_payroll_python_sdk.type.webhooks_create_subscription_request_subscription_types import WebhooksCreateSubscriptionRequestSubscriptionTypes

class RequiredWebhooksCreateSubscriptionRequest(TypedDict):
    url: str

    subscription_types: WebhooksCreateSubscriptionRequestSubscriptionTypes

class OptionalWebhooksCreateSubscriptionRequest(TypedDict, total=False):
    pass

class WebhooksCreateSubscriptionRequest(RequiredWebhooksCreateSubscriptionRequest, OptionalWebhooksCreateSubscriptionRequest):
    pass
