# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_plaid_processor_token.post import CreateFromPlaidTokenRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_bank_accounts.post import CreateVerificationDepositsRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_bank_accounts.get import ListCompanyBankAccountsRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_bank_accounts_bank_account_uuid_verify.put import VerifyMicroDepositsRaw


class BankAccountsApiRaw(
    CreateFromPlaidTokenRaw,
    CreateVerificationDepositsRaw,
    ListCompanyBankAccountsRaw,
    VerifyMicroDepositsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
