# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_plaid_processor_token.post import CreateFromPlaidToken
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_bank_accounts.post import CreateVerificationDeposits
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_bank_accounts.get import ListCompanyBankAccounts
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_bank_accounts_bank_account_uuid_verify.put import VerifyMicroDeposits
from gusto_embedded_payroll_python_sdk.apis.tags.bank_accounts_api_raw import BankAccountsApiRaw


class BankAccountsApi(
    CreateFromPlaidToken,
    CreateVerificationDeposits,
    ListCompanyBankAccounts,
    VerifyMicroDeposits,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BankAccountsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BankAccountsApiRaw(api_client)
