# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_partner_managed_companies_company_uuid_accept_terms_of_service.post import AcceptTermsOfServiceRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_admins.post import CreateAdminRaw
from gusto_embedded_payroll_python_sdk.paths.v1_partner_managed_companies.post import CreatePartnerManagedCompanyRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_uuid_finish_onboarding.put import FinishOnboardingRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_admins.get import GetAllAdminsRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id.get import GetCompanyRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_custom_fields.get import GetCustomFieldsRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_uuid_onboarding_status.get import GetOnboardingStatusRaw
from gusto_embedded_payroll_python_sdk.paths.v1_partner_managed_companies_company_uuid_retrieve_terms_of_service.post import GetTermsOfServiceStatusRaw
from gusto_embedded_payroll_python_sdk.paths.v1_partner_managed_companies_company_uuid_migrate.put import MigrateToEmbeddedPayrollRaw


class CompaniesApiRaw(
    AcceptTermsOfServiceRaw,
    CreateAdminRaw,
    CreatePartnerManagedCompanyRaw,
    FinishOnboardingRaw,
    GetAllAdminsRaw,
    GetCompanyRaw,
    GetCustomFieldsRaw,
    GetOnboardingStatusRaw,
    GetTermsOfServiceStatusRaw,
    MigrateToEmbeddedPayrollRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
