# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id_bank_accounts.post import CreateBankAccountRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id_bank_accounts_bank_account_uuid.delete import DeleteBankAccountRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id_payment_method.get import GetBankAccountsRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id_bank_accounts.get import ListBankAccountsRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id_payment_method.put import UpdatePaymentMethodRaw


class EmployeePaymentMethodApiRaw(
    CreateBankAccountRaw,
    DeleteBankAccountRaw,
    GetBankAccountsRaw,
    ListBankAccountsRaw,
    UpdatePaymentMethodRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
