# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id_finish_onboarding.put import CompleteOnboardingRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_employees.post import CreateEmployeeRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id.delete import DeleteOnboardingEmployeeRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id_custom_fields.get import GetCustomFieldsRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id.get import GetEmployeeByIdRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id_onboarding_status.get import GetOnboardingStatusRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_uuid_time_off_activities.get import GetTimeOffActivitiesRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_employees.get import ListCompanyEmployeesRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id.put import UpdateEmployeeRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_id_onboarding_status.put import UpdateOnboardingStatusRaw


class EmployeesApiRaw(
    CompleteOnboardingRaw,
    CreateEmployeeRaw,
    DeleteOnboardingEmployeeRaw,
    GetCustomFieldsRaw,
    GetEmployeeByIdRaw,
    GetOnboardingStatusRaw,
    GetTimeOffActivitiesRaw,
    ListCompanyEmployeesRaw,
    UpdateEmployeeRaw,
    UpdateOnboardingStatusRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
