# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_uuid_federal_taxes.get import GetFederalTaxesByIdRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_uuid_state_taxes.get import GetStateTaxesRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_uuid_federal_taxes.put import UpdateFederalTaxesRaw
from gusto_embedded_payroll_python_sdk.paths.v1_employees_employee_uuid_state_taxes.put import UpdateStateTaxesRaw


class EmployeeTaxSetupApiRaw(
    GetFederalTaxesByIdRaw,
    GetStateTaxesRaw,
    UpdateFederalTaxesRaw,
    UpdateStateTaxesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
