# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_federal_tax_details.get import GetAttributesRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_id_federal_tax_details.put import UpdateAttributesRaw


class FederalTaxDetailsApiRaw(
    GetAttributesRaw,
    UpdateAttributesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
