# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_notifications_notification_uuid.get import GetDetails
from gusto_embedded_payroll_python_sdk.apis.tags.notifications_api_raw import NotificationsApiRaw


class NotificationsApi(
    GetDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: NotificationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = NotificationsApiRaw(api_client)
