# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_uuid_payment_configs.get import GetCompanyPaymentConfigs
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_uuid_payment_configs.put import UpdateCompanyPaymentConfigs
from gusto_embedded_payroll_python_sdk.apis.tags.payment_configs_api_raw import PaymentConfigsApiRaw


class PaymentConfigsApi(
    GetCompanyPaymentConfigs,
    UpdateCompanyPaymentConfigs,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentConfigsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentConfigsApiRaw(api_client)
