# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_uuid_signatories_invite.post import CreateInviteRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_uuid_signatories.post import CreateSignatoryWithCompleteInformationRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_uuid_signatories_signatory_uuid.delete import DeleteSignatoryRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_uuid_signatories.get import GetCompanySignatoriesRaw
from gusto_embedded_payroll_python_sdk.paths.v1_companies_company_uuid_signatories_signatory_uuid.put import UpdateRaw


class SignatoriesApiRaw(
    CreateInviteRaw,
    CreateSignatoryWithCompleteInformationRaw,
    DeleteSignatoryRaw,
    GetCompanySignatoriesRaw,
    UpdateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
