# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest

import gusto_embedded_payroll_python_sdk
from gusto_embedded_payroll_python_sdk.model.employee_tax_setup_get_state_taxes_response import EmployeeTaxSetupGetStateTaxesResponse
from gusto_embedded_payroll_python_sdk import configuration


class TestEmployeeTaxSetupGetStateTaxesResponse(unittest.TestCase):
    """EmployeeTaxSetupGetStateTaxesResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
