# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest

import gusto_embedded_payroll_python_sdk
from gusto_embedded_payroll_python_sdk.model.jobs_and_compensations_create_compensation_request_minimum_wages import JobsAndCompensationsCreateCompensationRequestMinimumWages
from gusto_embedded_payroll_python_sdk import configuration


class TestJobsAndCompensationsCreateCompensationRequestMinimumWages(unittest.TestCase):
    """JobsAndCompensationsCreateCompensationRequestMinimumWages unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
