# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest

import gusto_embedded_payroll_python_sdk
from gusto_embedded_payroll_python_sdk.model.webhook_subscription import WebhookSubscription
from gusto_embedded_payroll_python_sdk import configuration


class TestWebhookSubscription(unittest.TestCase):
    """WebhookSubscription unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
