# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest

import gusto_embedded_payroll_python_sdk
from gusto_embedded_payroll_python_sdk.model.employee_benefits_create_ytd_benefit_amounts_from_different_company_request import EmployeeBenefitsCreateYtdBenefitAmountsFromDifferentCompanyRequest
from gusto_embedded_payroll_python_sdk import configuration


class TestEmployeeBenefitsCreateYtdBenefitAmountsFromDifferentCompanyRequest(unittest.TestCase):
    """EmployeeBenefitsCreateYtdBenefitAmountsFromDifferentCompanyRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
