# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gusto_embedded_payroll_python_sdk import schemas  # noqa: F401


class ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Submit wages, benefits, taxes for each employee
    """


    class MetaOapg:
        
        class properties:
            employee_uuid = schemas.StrSchema
        
            @staticmethod
            def earnings() -> typing.Type['ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemEarnings']:
                return ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemEarnings
        
            @staticmethod
            def benefits() -> typing.Type['ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemBenefits']:
                return ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemBenefits
        
            @staticmethod
            def taxes() -> typing.Type['ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemTaxes']:
                return ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemTaxes
            __annotations__ = {
                "employee_uuid": employee_uuid,
                "earnings": earnings,
                "benefits": benefits,
                "taxes": taxes,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employee_uuid"]) -> MetaOapg.properties.employee_uuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["earnings"]) -> 'ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemEarnings': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["benefits"]) -> 'ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemBenefits': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["taxes"]) -> 'ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemTaxes': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["employee_uuid", "earnings", "benefits", "taxes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employee_uuid"]) -> typing.Union[MetaOapg.properties.employee_uuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["earnings"]) -> typing.Union['ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemEarnings', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["benefits"]) -> typing.Union['ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemBenefits', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["taxes"]) -> typing.Union['ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemTaxes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["employee_uuid", "earnings", "benefits", "taxes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        employee_uuid: typing.Union[MetaOapg.properties.employee_uuid, str, schemas.Unset] = schemas.unset,
        earnings: typing.Union['ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemEarnings', schemas.Unset] = schemas.unset,
        benefits: typing.Union['ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemBenefits', schemas.Unset] = schemas.unset,
        taxes: typing.Union['ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemTaxes', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItem':
        return super().__new__(
            cls,
            *args,
            employee_uuid=employee_uuid,
            earnings=earnings,
            benefits=benefits,
            taxes=taxes,
            _configuration=_configuration,
            **kwargs,
        )

from gusto_embedded_payroll_python_sdk.model.external_payrolls_update_payroll_items_request_external_payroll_items_item_benefits import ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemBenefits
from gusto_embedded_payroll_python_sdk.model.external_payrolls_update_payroll_items_request_external_payroll_items_item_earnings import ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemEarnings
from gusto_embedded_payroll_python_sdk.model.external_payrolls_update_payroll_items_request_external_payroll_items_item_taxes import ExternalPayrollsUpdatePayrollItemsRequestExternalPayrollItemsItemTaxes
