# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gusto_embedded_payroll_python_sdk import schemas  # noqa: F401


class HolidayPayPoliciesCreateCompanyPolicyRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def federal_holidays() -> typing.Type['HolidayPayPoliciesCreateCompanyPolicyRequestFederalHolidays']:
                return HolidayPayPoliciesCreateCompanyPolicyRequestFederalHolidays
            __annotations__ = {
                "federal_holidays": federal_holidays,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["federal_holidays"]) -> 'HolidayPayPoliciesCreateCompanyPolicyRequestFederalHolidays': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["federal_holidays", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["federal_holidays"]) -> typing.Union['HolidayPayPoliciesCreateCompanyPolicyRequestFederalHolidays', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["federal_holidays", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        federal_holidays: typing.Union['HolidayPayPoliciesCreateCompanyPolicyRequestFederalHolidays', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'HolidayPayPoliciesCreateCompanyPolicyRequest':
        return super().__new__(
            cls,
            *args,
            federal_holidays=federal_holidays,
            _configuration=_configuration,
            **kwargs,
        )

from gusto_embedded_payroll_python_sdk.model.holiday_pay_policies_create_company_policy_request_federal_holidays import HolidayPayPoliciesCreateCompanyPolicyRequestFederalHolidays
