# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gusto_embedded_payroll_python_sdk import schemas  # noqa: F401


class PaymentConfigs(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            company_uuid = schemas.StrSchema
            partner_uuid = schemas.StrSchema
            fast_payment_limit = schemas.StrSchema
            payment_speed = schemas.StrSchema
            __annotations__ = {
                "company_uuid": company_uuid,
                "partner_uuid": partner_uuid,
                "fast_payment_limit": fast_payment_limit,
                "payment_speed": payment_speed,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["company_uuid"]) -> MetaOapg.properties.company_uuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["partner_uuid"]) -> MetaOapg.properties.partner_uuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fast_payment_limit"]) -> MetaOapg.properties.fast_payment_limit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payment_speed"]) -> MetaOapg.properties.payment_speed: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["company_uuid", "partner_uuid", "fast_payment_limit", "payment_speed", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["company_uuid"]) -> typing.Union[MetaOapg.properties.company_uuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["partner_uuid"]) -> typing.Union[MetaOapg.properties.partner_uuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fast_payment_limit"]) -> typing.Union[MetaOapg.properties.fast_payment_limit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payment_speed"]) -> typing.Union[MetaOapg.properties.payment_speed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["company_uuid", "partner_uuid", "fast_payment_limit", "payment_speed", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        company_uuid: typing.Union[MetaOapg.properties.company_uuid, str, schemas.Unset] = schemas.unset,
        partner_uuid: typing.Union[MetaOapg.properties.partner_uuid, str, schemas.Unset] = schemas.unset,
        fast_payment_limit: typing.Union[MetaOapg.properties.fast_payment_limit, str, schemas.Unset] = schemas.unset,
        payment_speed: typing.Union[MetaOapg.properties.payment_speed, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaymentConfigs':
        return super().__new__(
            cls,
            *args,
            company_uuid=company_uuid,
            partner_uuid=partner_uuid,
            fast_payment_limit=fast_payment_limit,
            payment_speed=payment_speed,
            _configuration=_configuration,
            **kwargs,
        )
