# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gusto_embedded_payroll_python_sdk import schemas  # noqa: F401


class PayrollEmployeeCompensationsTypeItemBenefitsItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            name = schemas.StrSchema
            employee_deduction = schemas.StrSchema
            company_contribution = schemas.StrSchema
            imputed = schemas.BoolSchema
            __annotations__ = {
                "name": name,
                "employee_deduction": employee_deduction,
                "company_contribution": company_contribution,
                "imputed": imputed,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employee_deduction"]) -> MetaOapg.properties.employee_deduction: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["company_contribution"]) -> MetaOapg.properties.company_contribution: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["imputed"]) -> MetaOapg.properties.imputed: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "employee_deduction", "company_contribution", "imputed", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employee_deduction"]) -> typing.Union[MetaOapg.properties.employee_deduction, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["company_contribution"]) -> typing.Union[MetaOapg.properties.company_contribution, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["imputed"]) -> typing.Union[MetaOapg.properties.imputed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "employee_deduction", "company_contribution", "imputed", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        employee_deduction: typing.Union[MetaOapg.properties.employee_deduction, str, schemas.Unset] = schemas.unset,
        company_contribution: typing.Union[MetaOapg.properties.company_contribution, str, schemas.Unset] = schemas.unset,
        imputed: typing.Union[MetaOapg.properties.imputed, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayrollEmployeeCompensationsTypeItemBenefitsItem':
        return super().__new__(
            cls,
            *args,
            name=name,
            employee_deduction=employee_deduction,
            company_contribution=company_contribution,
            imputed=imputed,
            _configuration=_configuration,
            **kwargs,
        )
