# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gusto_embedded_payroll_python_sdk import schemas  # noqa: F401


class PayrollCheck(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            payroll_uuid = schemas.StrSchema
            printing_format = schemas.StrSchema
            starting_check_number = schemas.StrSchema
            request_uuid = schemas.StrSchema
            status = schemas.StrSchema
            __annotations__ = {
                "payroll_uuid": payroll_uuid,
                "printing_format": printing_format,
                "starting_check_number": starting_check_number,
                "request_uuid": request_uuid,
                "status": status,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payroll_uuid"]) -> MetaOapg.properties.payroll_uuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["printing_format"]) -> MetaOapg.properties.printing_format: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["starting_check_number"]) -> MetaOapg.properties.starting_check_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["request_uuid"]) -> MetaOapg.properties.request_uuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["payroll_uuid", "printing_format", "starting_check_number", "request_uuid", "status", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payroll_uuid"]) -> typing.Union[MetaOapg.properties.payroll_uuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["printing_format"]) -> typing.Union[MetaOapg.properties.printing_format, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["starting_check_number"]) -> typing.Union[MetaOapg.properties.starting_check_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["request_uuid"]) -> typing.Union[MetaOapg.properties.request_uuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["payroll_uuid", "printing_format", "starting_check_number", "request_uuid", "status", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        payroll_uuid: typing.Union[MetaOapg.properties.payroll_uuid, str, schemas.Unset] = schemas.unset,
        printing_format: typing.Union[MetaOapg.properties.printing_format, str, schemas.Unset] = schemas.unset,
        starting_check_number: typing.Union[MetaOapg.properties.starting_check_number, str, schemas.Unset] = schemas.unset,
        request_uuid: typing.Union[MetaOapg.properties.request_uuid, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayrollCheck':
        return super().__new__(
            cls,
            *args,
            payroll_uuid=payroll_uuid,
            printing_format=printing_format,
            starting_check_number=starting_check_number,
            request_uuid=request_uuid,
            status=status,
            _configuration=_configuration,
            **kwargs,
        )
