# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gusto_embedded_payroll_python_sdk import schemas  # noqa: F401


class TimeOffPoliciesAddEmployeesToPolicyRequestEmployees(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['TimeOffPoliciesAddEmployeesToPolicyRequestEmployeesItem']:
            return TimeOffPoliciesAddEmployeesToPolicyRequestEmployeesItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['TimeOffPoliciesAddEmployeesToPolicyRequestEmployeesItem'], typing.List['TimeOffPoliciesAddEmployeesToPolicyRequestEmployeesItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'TimeOffPoliciesAddEmployeesToPolicyRequestEmployees':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'TimeOffPoliciesAddEmployeesToPolicyRequestEmployeesItem':
        return super().__getitem__(i)

from gusto_embedded_payroll_python_sdk.model.time_off_policies_add_employees_to_policy_request_employees_item import TimeOffPoliciesAddEmployeesToPolicyRequestEmployeesItem
