# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class BankAccountsVerifyMicroDepositsRequest(BaseModel):
    # The dollar amount of the first micro-deposit
    deposit_1: typing.Optional[typing.Union[int, float]] = Field(None, alias='deposit_1')

    # The dollar amount of the second micro-deposit
    deposit_2: typing.Optional[typing.Union[int, float]] = Field(None, alias='deposit_2')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
