# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from gusto_embedded_payroll_python_sdk.pydantic.benefit_summary_employees_payroll_benefits import BenefitSummaryEmployeesPayrollBenefits

class BenefitSummaryEmployees(BaseModel):
    # The UUID of the employee
    uuid: typing.Optional[str] = Field(None, alias='uuid')

    # The aggregate of employee deduction for all employees given the period of time and benefit type.
    company_benefit_deduction: typing.Optional[str] = Field(None, alias='company_benefit_deduction')

    # The aggregate of company contribution for all employees given the period of time and benefit type.
    company_benefit_contribution: typing.Optional[str] = Field(None, alias='company_benefit_contribution')

    # Sum of employee benefit deduction given the period of time for this specific employee.
    benefit_deduction: typing.Optional[str] = Field(None, alias='benefit_deduction')

    # Sum of company contribution given the period of time for this specific employee.
    benefit_contribution: typing.Optional[str] = Field(None, alias='benefit_contribution')

    # Gross pay of this pay check.
    gross_pay: typing.Optional[str] = Field(None, alias='gross_pay')

    payroll_benefits: typing.Optional[BenefitSummaryEmployeesPayrollBenefits] = Field(None, alias='payroll_benefits')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
