# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from gusto_embedded_payroll_python_sdk.pydantic.contractor_payments_preview_debit_date_request_contractor_payments import ContractorPaymentsPreviewDebitDateRequestContractorPayments

class ContractorPaymentsPreviewDebitDateRequest(BaseModel):
    contractor_payments: typing.Optional[ContractorPaymentsPreviewDebitDateRequestContractorPayments] = Field(None, alias='contractor_payments')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
