# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ContractorPaymentMethodCreateBankAccountRequest(BaseModel):
    name: str = Field(alias='name')

    routing_number: str = Field(alias='routing_number')

    account_number: str = Field(alias='account_number')

    account_type: Literal["Checking", "Savings"] = Field(alias='account_type')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
