# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ContractorBody(BaseModel):
    # The contractor type.
    type: typing.Optional[Literal["Individual", "Business"]] = Field(None, alias='type')

    # The contractor’s wage type. 
    wage_type: typing.Optional[Literal["Fixed", "Hourly"]] = Field(None, alias='wage_type')

    # The day when the contractor will start working for the company. 
    start_date: typing.Optional[str] = Field(None, alias='start_date')

    # The contractor’s hourly rate. This attribute is required if the wage_type is `Hourly`.
    hourly_rate: typing.Optional[str] = Field(None, alias='hourly_rate')

    # Whether the contractor or the payroll admin will complete onboarding in Gusto. Self-onboarding is recommended so that contractors receive Gusto accounts. If self_onboarding is true, then email is required.
    self_onboarding: typing.Optional[bool] = Field(None, alias='self_onboarding')

    # The contractor’s email address.
    email: typing.Optional[str] = Field(None, alias='email')

    # The contractor’s first name. This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
    first_name: typing.Optional[str] = Field(None, alias='first_name')

    # The contractor’s last name. This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
    last_name: typing.Optional[str] = Field(None, alias='last_name')

    # The contractor’s middle initial. This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
    middle_initial: typing.Optional[str] = Field(None, alias='middle_initial')

    # The boolean flag indicating whether Gusto will file a new hire report for the contractor. This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
    file_new_hire_report: typing.Optional[bool] = Field(None, alias='file_new_hire_report')

    # State where the contractor will be conducting the majority of their work for the company. This value is used when generating the new hire report. This attribute is required for `Individual` contractors if `file_new_hire_report` is true and will be ignored for `Business` contractors.
    work_state: typing.Optional[typing.Optional[str]] = Field(None, alias='work_state')

    # This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors. Social security number is needed to file the annual 1099 tax form.
    ssn: typing.Optional[str] = Field(None, alias='ssn')

    # The name of the contractor business. This attribute is required for `Business` contractors and will be ignored for `Individual` contractors.
    business_name: typing.Optional[str] = Field(None, alias='business_name')

    # The employer identification number of the contractor business. This attribute is optional for `Business` contractors and will be ignored for `Individual` contractors.
    ein: typing.Optional[str] = Field(None, alias='ein')

    # The status of the contractor.
    is_active: typing.Optional[bool] = Field(None, alias='is_active')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
