# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from gusto_embedded_payroll_python_sdk.pydantic.employee_state_tax_answer import EmployeeStateTaxAnswer
from gusto_embedded_payroll_python_sdk.pydantic.employee_state_tax_input_question_format import EmployeeStateTaxInputQuestionFormat

class EmployeeStateTaxQuestion(BaseModel):
    # An explaination of the question - this may contain inline html formatted links.
    description: str = Field(alias='description')

    # A short title for the question
    label: str = Field(alias='label')

    # A unique identifier of the question (for the given state) - used for updating the answer.
    key: str = Field(alias='key')

    input_question_format: EmployeeStateTaxInputQuestionFormat = Field(alias='input_question_format')

    answers: typing.List[EmployeeStateTaxAnswer] = Field(alias='answers')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
