# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class FederalTaxDetailsUpdateAttributesRequest(BaseModel):
    # The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field.
    version: str = Field(alias='version')

    # The legal name of the company
    legal_name: typing.Optional[str] = Field(None, alias='legal_name')

    # The EIN of of the company
    ein: typing.Optional[str] = Field(None, alias='ein')

    # What type of tax entity the company is
    tax_payer_type: typing.Optional[Literal["C-Corporation", "S-Corporation", "Sole proprietor", "LLC", "LLP", "Limited partnership", "Co-ownership", "Association", "Trusteeship", "General partnership", "Joint venture", "Non-Profit"]] = Field(None, alias='tax_payer_type')

    # The form used by the company for federal tax filing. One of: - 941 (Quarterly federal tax return) - 944 (Annual federal tax return)
    filing_form: typing.Optional[str] = Field(None, alias='filing_form')

    # Whether this company should be taxed as an S-Corporation
    taxable_as_scorp: typing.Optional[bool] = Field(None, alias='taxable_as_scorp')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
