# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class HolidayPayPoliciesPreviewCompanyPaidHolidaysRequest(BaseModel):
    # If a year is passed, paid holidays for that year will be returned. Otherwise, paid holidays for the next three years will be returned.
    year: typing.Optional[str] = Field(None, alias='year')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
