# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class IntrospectionExchangeRefreshTokenRequest(BaseModel):
    # Your client id
    client_id: str = Field(alias='client_id')

    # Your client secret
    client_secret: str = Field(alias='client_secret')

    # The `refresh_token` being exchanged for an access token code
    refresh_token: str = Field(alias='refresh_token')

    # this should be the literal string 'refresh_token'
    grant_type: str = Field(alias='grant_type')

    # The redirect URI you set up via the Developer Portal
    redirect_uri: typing.Optional[str] = Field(None, alias='redirect_uri')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
