# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class TaxRequirementMetadataOptionsItem(BaseModel):
    # A customer facing label for the answer
    label: str = Field(alias='label')

    # The actual value to be submitted
    value: str = Field(alias='value')

    # A less verbose label that may sometimes be available
    short_label: typing.Optional[str] = Field(None, alias='short_label')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
