# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from gusto_embedded_payroll_python_sdk.pydantic.tax_requirement import TaxRequirement
from gusto_embedded_payroll_python_sdk.pydantic.tax_requirement_effective_from import TaxRequirementEffectiveFrom

class TaxRequirementSet(BaseModel):
    # One of the two-letter state abbreviations for the fifty United States and the District of Columbia (DC)
    state: typing.Optional[str] = Field(None, alias='state')

    # An identifier for a set of requirements. A list of requirement sets can contain multiple sets with the same `key` and different `effective_from` values.
    key: typing.Optional[str] = Field(None, alias='key')

    # Customer facing label for the requirement set, e.g. \"Registrations\"
    label: typing.Optional[str] = Field(None, alias='label')

    effective_from: typing.Optional[TaxRequirementEffectiveFrom] = Field(None, alias='effective_from')

    requirements: typing.Optional[typing.List[TaxRequirement]] = Field(None, alias='requirements')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
