# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class TaxRequirementApplicableIfItem(BaseModel):
    # An identifier for an individual requirement. Uniqueness is guaranteed within a requirement set.
    key: typing.Optional[str] = Field(None, alias='key')

    # The required value of the requirement identified by `key`
    value: typing.Optional[typing.Union[bool, str, typing.Union[int, float]]] = Field(None, alias='value')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
