# coding: utf-8

"""
    Gusto API

    Welcome to Gusto's Embedded Payroll API documentation!

    The version of the OpenAPI document: 2024-03-01
    Contact: developer@gusto.com
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import gusto_embedded_payroll_python_sdk
from gusto_embedded_payroll_python_sdk.paths.v1_partner_managed_companies_company_uuid_retrieve_terms_of_service import post
from gusto_embedded_payroll_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1PartnerManagedCompaniesCompanyUuidRetrieveTermsOfService(ApiTestMixin, unittest.TestCase):
    """
    V1PartnerManagedCompaniesCompanyUuidRetrieveTermsOfService unit test stubs
        Retrieve terms of service status for a company user
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
